version: 2.1

orbs:
  bedrock-plugin-disabler:
    executors:
      php-73:
        docker:
          - image: 'cimg/php:7.3'
      php-72:
        docker:
          - image: 'cimg/php:7.2'
      php-71:
        docker:
          - image: 'cimg/php:7.1'
      php-70:
        docker:
          - image: 'cimg/php:7.0'
      php-56:
        docker:
          - image: 'cimg/php:5.6'
    jobs:
      build-php:
        parameters:
          executor:
            type: executor
        executor: << parameters.executor >>
        steps:
          - run: php -v
          - checkout
          - restore_cache:
              keys:
                - composer-v1-{{ checksum "composer.lock" }}
                - composer-v1-
          - run: composer install -n --prefer-dist
          - run: composer lint
          - save_cache:
              key: composer-v1-{{ checksum "composer.lock" }}
              paths:
                - vendor

workflows:
  build:
    jobs:
      - bedrock-plugin-disabler/build-php:
          name: build-php-73
          executor: bedrock-plugin-disabler/php-73
      - bedrock-plugin-disabler/build-php:
          name: build-php-72
          executor: bedrock-plugin-disabler/php-72
      - bedrock-plugin-disabler/build-php:
          name: build-php-71
          executor: bedrock-plugin-disabler/php-71
      - bedrock-plugin-disabler/build-php:
          name: build-php-70
          executor: bedrock-plugin-disabler/php-70
      - bedrock-plugin-disabler/build-php:
          name: build-php-56
          executor: bedrock-plugin-disabler/php-56
